IF
	AreaCheck("AR0602")
	!Global("d2ngepic","GLOBAL",1)
	!PartyHasItem("d2#ngbag")
	HasItem("lhMIS0a",Player1)
THEN
	RESPONSE #100
		GiveItemCreate("d2#ngbag",Player1,0,0,0)
		SetGlobal("d2ngepic","GLOBAL",1)
		Continue()
END

IF
	AreaCheck("AR0602")
	!Global("d2ngepicbagdupe","GLOBAL",1)
	Global("d2ngepic","GLOBAL",1)
	NumItemsGT("d2#ngbag",Player1,1)
THEN
	RESPONSE #100
		ActionOverride(Player1,DestroyItem("d2#ngbag"))
		SetGlobal("d2ngepicbagdupe","GLOBAL",1)
END