//
//


ACTION_IF !(IS_AN_INT d2script_fixNIwarnings) BEGIN

  OUTER_SET d2script_fixNIwarnings = 1


//this is for games that don't use .pro files
//deletes projectl.ids and missile.ids if a mod added them (these are used for .pro files)
//having these files in the override can mess with editors like NI
ACTION_IF (GAME_IS ~bg1 totsc iwd how totlm iwd2 pst~) BEGIN

  OUTER_SET delete_pro = 0
  ACTION_FOR_EACH file IN ~projectl~ ~missile~ BEGIN
    ACTION_IF (FILE_EXISTS ~override/%file%.ids~) BEGIN
      DELETE ~override/%file%.ids~
      OUTER_SET delete_pro = 1
    END
  END

  ACTION_IF (delete_pro > 0) BEGIN
    ACTION_BASH_FOR ~override~ ~.*\.pro$~ BEGIN    // delete PRO files (not supported by game)
      DELETE ~%BASH_FOR_FILESPEC%~
    END
  END
END



//
//tutu: overwrite possible bad items (not used but shows annoying NI warnings)
ACTION_IF (GAME_IS ~bg2 tob tutu tutu_totsc iwd_in_bg2 ca~) BEGIN
  ACTION_FOR_EACH item IN ~plot01k~ ~plot04g~ ~plot04h~ ~plot04i~ BEGIN
    OUTER_SPRINT base  ~override/%item%.itm~
    OUTER_SPRINT error  ~override/i%item%.itm~
    ACTION_IF (FILE_EXISTS ~%error%~) BEGIN
      COPY_EXISTING ~%base%~  ~%error%~ IF_EXISTS
    END
  END
END


END


//
//