[settings file, set before install]

# for Starting items tweak (both options)
# 1 = uses baldur.bcs + area script + invisible CREs (default)
# 0 = uses area script + invisible CREs (note: eet/bgt always use this mode)
useglobalscript = 1
