/*
for testing - alt with less global scripting
*/


INCLUDE ~%install%/ngitemprep.tph~
INCLUDE ~%install%/ngitemcre.tph~
INCLUDE ~%install%/ngitemprofs.tph~

<<<<<<<< .../temp/newfile
//
>>>>>>>>
COPY - ~.../temp/newfile~  ~inlined/newfile~

////////////////////////////////////////////////////////////

ACTION_IF (GAME_IS ~iwdee bgee eet~) BEGIN

  LAF ngitemprofs RET createitems END    // "createitems" includes class/melee/ranged script blocks

  COPY - ~inlined/newfile~  ~inlined/slot1.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_ee_top.BAF~
    APPEND_FILE TEXT ~%createitems%~
//    APPEND_FILE TEXT ~%ngequip%/ngequip_ee_class.BAF~
//    APPEND_FILE TEXT ~%ngequip%/ngequip_ee_melee.BAF~
//    APPEND_FILE TEXT ~%ngequip%/ngequip_ee_ranged.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_ee_end.BAF~
    EVALUATE_BUFFER

    // extra patching
    PATCH_IF !(FILE_EXISTS_IN_GAME ~%greataxe%.itm~) BEGIN
      REPLACE_TEXTUALLY ~"%greataxe%"~  ~"%axe%"~
      REPLACE_TEXTUALLY ~%greataxe_prof%~  ~%axe_prof%~
      REPLACE_TEXTUALLY ~%greataxe_strcheck%~  ~%axe_strcheck%~
    END

  COPY - ~inlined/slot1.BAF~  ~inlined/slot2.BAF~    // run for each PC
    REPLACE_TEXTUALLY ~Player1~  ~Player2~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot3.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player3~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot4.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player4~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot5.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player5~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot6.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player6~

  COPY - ~inlined/slot1.BAF~  ~inlined/ngitems.BAF~    // combine script
    APPEND_FILE TEXT ~inlined/slot2.BAF~
    APPEND_FILE TEXT ~inlined/slot3.BAF~
    APPEND_FILE TEXT ~inlined/slot4.BAF~
    APPEND_FILE TEXT ~inlined/slot5.BAF~
    APPEND_FILE TEXT ~inlined/slot6.BAF~

  // iwdee scripts
  ACTION_IF (RESOURCE_CONTAINS ~ar1006.are~  ~hroth~) BEGIN
    EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/ngitems.BAF~    // add script
    EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/timer.BAF~
    EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/string.BAF~
  END

  // bgee scripts
  ACTION_FOR_EACH script IN ~ar2600~ ~bg2600~ BEGIN
    ACTION_IF (RESOURCE_CONTAINS ~%script%.are~  ~imoen~) BEGIN
      EXTEND_BOTTOM ~%script%.BCS~  ~inlined/ngitems.BAF~
      EXTEND_BOTTOM ~%script%.BCS~  ~inlined/timer.BAF~
      EXTEND_BOTTOM ~%script%.BCS~  ~inlined/string.BAF~
    END
  END

//  EXTEND_BOTTOM ~BALDUR.BCS~  ~inlined/ngitems.BAF~
  LAF ngequipcre END    // invisible creature

END

////////////////////////////////////////////////////////////

ACTION_IF (GAME_IS ~iwd how totlm~) BEGIN

  INCLUDE ~%install%/ngiwd1items.tph~    // blocks for adding weapons (inlined)

/*
COPY - ~.../temp/blocks~  ~inlined/blunt.BAF~
COPY - ~.../temp/blocks~  ~inlined/warrior.BAF~
COPY - ~.../temp/blocks~  ~inlined/thief.BAF~
COPY - ~.../temp/blocks~  ~inlined/ranged.BAF~
*/

  COPY - ~inlined/newfile~  ~inlined/slot1.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_top.BAF~
    APPEND_FILE TEXT ~inlined/thief.BAF~
    APPEND_FILE TEXT ~inlined/ranged.BAF~
    APPEND_FILE TEXT ~inlined/blunt.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_end.BAF~
    SPRINT target  ~Player1~
    EVALUATE_BUFFER

  COPY - ~inlined/newfile~  ~inlined/slot2.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_top.BAF~
    APPEND_FILE TEXT ~inlined/warrior.BAF~
    APPEND_FILE TEXT ~inlined/blunt.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_end.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player2~
    SPRINT target  ~Player2~
    EVALUATE_BUFFER

  COPY - ~inlined/newfile~  ~inlined/slot3.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_top.BAF~
    APPEND_FILE TEXT ~inlined/thief.BAF~
    APPEND_FILE TEXT ~inlined/ranged.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_end.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player3~
    SPRINT target  ~Player2~
    EVALUATE_BUFFER

  COPY - ~inlined/newfile~  ~inlined/slot4.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_top.BAF~
    APPEND_FILE TEXT ~inlined/warrior.BAF~
    APPEND_FILE TEXT ~inlined/ranged.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_end.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player4~
    SPRINT target  ~Player2~
    EVALUATE_BUFFER

  COPY - ~inlined/newfile~  ~inlined/slot5.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_top.BAF~
    APPEND_FILE TEXT ~inlined/blunt.BAF~
    APPEND_FILE TEXT ~inlined/thief.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_end.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player5~
    SPRINT target  ~Player2~
    EVALUATE_BUFFER

  COPY - ~inlined/newfile~  ~inlined/slot6.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_top.BAF~
    APPEND_FILE TEXT ~inlined/warrior.BAF~
    APPEND_FILE TEXT ~inlined/ranged.BAF~
//    APPEND_FILE TEXT ~inlined/thief.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd1_end.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player6~
    SPRINT target  ~Player1~
    EVALUATE_BUFFER

  COPY - ~inlined/slot1.BAF~  ~inlined/ngitems.BAF~
    APPEND_FILE TEXT ~inlined/slot2.BAF~
    APPEND_FILE TEXT ~inlined/slot3.BAF~
    APPEND_FILE TEXT ~inlined/slot4.BAF~
    APPEND_FILE TEXT ~inlined/slot5.BAF~
    APPEND_FILE TEXT ~inlined/slot6.BAF~

  EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/ngitems.BAF~
  EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/timer.BAF~
  EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/string.BAF~
//  EXTEND_BOTTOM ~BALDUR.BCS~  ~inlined/ngitems.BAF~

  EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/swordcheck.BAF~
  EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/bowcheck.BAF~
  EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/axecheck.BAF~
  EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/flailcheck.BAF~

END

////////////////////////////////////////////////////////////

ACTION_IF (GAME_IS ~iwd2~) BEGIN

  OUTER_SET iwd2npc = 0
  ACTION_IF (FILE_EXISTS ~Characters/SIR_NORD.CHR~) BEGIN OUTER_SET iwd2npc = 1 END
  ACTION_IF (FILE_EXISTS_IN_GAME ~avweapga.itm~) BEGIN OUTER_SET iwd2npc = 1 END

  COPY - ~inlined/newfile~  ~inlined/slot1.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd2_top.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd2_racial.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd2_melee.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd2_ranged.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd2_equipm.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd2_equipr.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_iwd2_end.BAF~
    EVALUATE_BUFFER

    // extra patching
    PATCH_IF (iwd2npc > 0) BEGIN
      SPRINT match   ~!HasItem("00ROBE03",Player1)~
      SPRINT string  ~!HasItem("AVROBEER",Player1)~
      REPLACE_TEXTUALLY EXACT_MATCH ~%match%~  ~%match%%WNL%%TAB%%string%~
    END ELSE BEGIN
      REPLACE_TEXTUALLY ~!InParty~  ~//~
    END

  COPY - ~inlined/slot1.BAF~  ~inlined/slot2.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player2~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot3.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player3~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot4.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player4~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot5.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player5~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot6.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player6~

  COPY - ~inlined/slot1.BAF~  ~inlined/ngitems.BAF~
    APPEND_FILE TEXT ~inlined/slot2.BAF~
    APPEND_FILE TEXT ~inlined/slot3.BAF~
    APPEND_FILE TEXT ~inlined/slot4.BAF~
    APPEND_FILE TEXT ~inlined/slot5.BAF~
    APPEND_FILE TEXT ~inlined/slot6.BAF~

  EXTEND_BOTTOM ~ar1000.BCS~  ~inlined/ngitems.BAF~
  EXTEND_BOTTOM ~ar1000.BCS~  ~inlined/timer.BAF~
  EXTEND_BOTTOM ~ar1000.BCS~  ~inlined/string.BAF~
//  EXTEND_BOTTOM ~BALDUR.BCS~  ~inlined/ngitems.BAF~

  LAF ngequipcre INT_VAR iwd2=1 END

END

////////////////////////////////////////////////////////////

ACTION_IF (GAME_IS ~iwd_in_bg2 ca bgt tutu tutu_totsc~) BEGIN

  LAF ngitemprofs INT_VAR bg2mode=1 RET createitems END

  COPY - ~inlined/newfile~  ~inlined/slot1.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_bg2_top.BAF~
    APPEND_FILE TEXT ~%createitems%~
//    APPEND_FILE TEXT ~%ngequip%/ngequip_bg2_class.BAF~
//    APPEND_FILE TEXT ~%ngequip%/ngequip_bg2_melee.BAF~
//    APPEND_FILE TEXT ~%ngequip%/ngequip_bg2_ranged.BAF~
    APPEND_FILE TEXT ~%ngequip%/ngequip_bg2_end.BAF~
    EVALUATE_BUFFER

    // extra patching
    PATCH_IF !(FILE_EXISTS_IN_GAME ~%greataxe%.itm~) BEGIN
      REPLACE_TEXTUALLY ~"%greataxe%"~  ~"%axe%"~
      REPLACE_TEXTUALLY ~%greataxe_prof%~  ~%axe_prof%~
      REPLACE_TEXTUALLY ~%greataxe_strcheck%~  ~%axe_strcheck%~
    END

/*
    PATCH_IF (RESOURCE_CONTAINS ~TC0009.bcs~ ~TC0009~) BEGIN
      SPRINT match    ~HasItem("%staff%",Player1)~
      SPRINT trigger  ~Global("NewGame","TC0009",1)~
//      REPLACE_TEXTUALLY EXACT_MATCH ~%match%~  ~%trigger%~    // ca - delay script until after variable
    END ELSE BEGIN
      SPRINT match  ~^.*DestroyItem~
      SPRINT string  ~//~
      REPLACE_TEXTUALLY EXACT_MATCH ~%match%~  ~%trigger%~    // iwd-in-bg2 - keep starting staff
    END
*/

  COPY - ~inlined/slot1.BAF~  ~inlined/slot2.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player2~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot3.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player3~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot4.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player4~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot5.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player5~
  COPY - ~inlined/slot1.BAF~  ~inlined/slot6.BAF~
    REPLACE_TEXTUALLY ~Player1~  ~Player6~

  COPY - ~inlined/slot1.BAF~  ~inlined/ngitems.BAF~
    APPEND_FILE TEXT ~inlined/slot2.BAF~
    APPEND_FILE TEXT ~inlined/slot3.BAF~
    APPEND_FILE TEXT ~inlined/slot4.BAF~
    APPEND_FILE TEXT ~inlined/slot5.BAF~
    APPEND_FILE TEXT ~inlined/slot6.BAF~

  // iwd-in-bg2
  ACTION_IF (RESOURCE_CONTAINS ~ar1006.are~  ~hroth~) BEGIN
    EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/ngitems.BAF~
    EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/timer.BAF~
    EXTEND_BOTTOM ~ar1006.BCS~  ~inlined/string.BAF~
  END

  // ca
  ACTION_IF (RESOURCE_CONTAINS ~TC0009.bcs~ ~TC0009~) BEGIN
    EXTEND_BOTTOM ~TC0009.BCS~  ~inlined/ngitems.BAF~
    EXTEND_BOTTOM ~TC0009.BCS~  ~inlined/timer.BAF~
    EXTEND_BOTTOM ~TC0009.BCS~  ~inlined/string.BAF~
  END

  // tutu
  ACTION_IF (RESOURCE_CONTAINS ~FW2600.are~  ~imoen~) BEGIN
    EXTEND_BOTTOM ~_AR2600.BCS~  ~inlined/ngitems.BAF~
    EXTEND_BOTTOM ~_AR2600.BCS~  ~inlined/timer.BAF~
    EXTEND_BOTTOM ~_AR2600.BCS~  ~inlined/string.BAF~
  END

  // bgt
  ACTION_IF (RESOURCE_CONTAINS ~AR0015.are~  ~imoen~) BEGIN
    EXTEND_BOTTOM ~AR0015.BCS~  ~inlined/ngitems.BAF~
    EXTEND_BOTTOM ~AR0015.BCS~  ~inlined/timer.BAF~
    EXTEND_BOTTOM ~AR0015.BCS~  ~inlined/string.BAF~
  END

//  EXTEND_BOTTOM ~BALDUR.BCS~  ~inlined/ngitems.BAF~
  LAF ngequipcre INT_VAR bg2mode=1 END

END

////////////////////////////////////////////////////////////

LAF 2flamingoils END


//
//