/*
test adding invisible creatures directly to area
observation: negligible difference from adding CREs by script
*/


DEFINE_ACTION_FUNCTION testCREarea BEGIN
  ACTION_FOR_EACH area IN
//    ~bg2600.are~
//    ~AR0015.are~
    ~ar1000.are~
  BEGIN
//  ACTION_IF (RESOURCE_CONTAINS ~%area%~  ~imoen~) BEGIN
      COPY_EXISTING ~%area%~  ~override~
        LPF testCREarea INT_VAR num=1 END
        LPF testCREarea INT_VAR num=2 END
        LPF testCREarea INT_VAR num=3 END
        LPF testCREarea INT_VAR num=4 END
        LPF testCREarea INT_VAR num=5 END
        LPF testCREarea INT_VAR num=6 END
      BUT_ONLY
//  END
  END
END

DEFINE_PATCH_FUNCTION testCREarea INT_VAR num=1 BEGIN
  PATCH_IF (~%SOURCE_EXT%~ STR_EQ ~are~) BEGIN
    LPF fj_are_structure
      INT_VAR
        fj_loc_x          = num
        fj_loc_y          = num
        fj_animation      = 0xD300
        fj_orientation    = 0
      STR_VAR
        fj_structure_type = actor
        fj_name           = Bird
        fj_cre_resref     = ~d2ngcre%num%~
    END
  END
END

LAF testCREarea END


/*
*/