/*
nymph script
*/


INCLUDE ~%install%/nymphprep.tph~

//set script for nymph (if changed by a mod)
COPY_EXISTING ~NYMPHSU.CRE~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
    WRITE_ASCII 0x248 NYMPH #8
  END
BUT_ONLY

//speed bonus
COPY ~%nymph%/nymphspeed.SPL~  ~override/d2cwfey.SPL~
  PATCH_IF (ee_type > 0) BEGIN
    LPF d2_remove_effects_on_cast END
  END



//add entangle variant

//functions
DEFINE_PATCH_FUNCTION spell_edits INT_VAR proj=1 BEGIN
  LPF ALTER_SPELL_HEADER INT_VAR range=1000 projectile=proj END
  WRITE_LONG 0x18 (THIS | BIT25)
  WRITE_LONG 0x18 (THIS BAND BNOT BIT10)    // non-hostile (unless damage taken)
  LPF ALTER_EFFECT INT_VAR silent=1 STR_VAR match_resource=~%SOURCE_RES%~ resource=~%DEST_RES%~ END

  PATCH_IF (ee_type > 0) BEGIN
//  LPF d2_safe_spell INT_VAR block_opcode=154 END    // not needed: projectile is enemies only
  END
END

DEFINE_PATCH_FUNCTION entangle_edits INT_VAR savebonus=0 duration=8 acdebuff=1 acsaves=1 nostacking=0 BEGIN
  // 8 seconds entangle (normally 7 in iwd and 9 in bg2)
  LPF ALTER_EFFECT INT_VAR silent=1 match_timing=0 duration=duration END
  LPF ALTER_EFFECT INT_VAR silent=1 match_timing=4 duration=duration END
  LPF ALTER_EFFECT INT_VAR silent=1 match_opcode=318 match_timing=0 duration=0 END
  LPF ALTER_EFFECT INT_VAR silent=1 match_opcode=324 match_timing=0 duration=0 END

  // add -2 ac penalty if it doesn't already have it
  PATCH_IF (acdebuff > 0) BEGIN
    READ_LONG 0x34 power
    LPF DELETE_EFFECT INT_VAR match_opcode=0 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode=0 target=2 power=power parameter1=(0 - 2) resist_dispel=1 duration=duration savingthrow=acsaves END
  END

  // prevent stacking with Entangle spell (note: BG1EE is the only game that prevents stacking entangles)
  PATCH_IF (nostacking > 0) BEGIN
    PATCH_IF (ee_game > 0) BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode=154 opcode=321 parameter2=0 timing=1 duration=0 STR_VAR resource=~%DEST_RES%~ insert=first END
      LPF CLONE_EFFECT INT_VAR match_opcode=154 opcode=321 parameter2=0 timing=1 duration=0 STR_VAR resource=SPPR105 insert=first END
    END
    LPF CLONE_EFFECT INT_VAR match_opcode=154 opcode=206 parameter1=0 duration=(duration - 1) STR_VAR resource=SPPR105 insert=first END
  END

  // save bonus
  LPF ALTER_EFFECT INT_VAR savebonus=savebonus END
  PATCH_IF (savebonus != 0) BEGIN
    LPF ALTER_EFFECT INT_VAR silent=1 match_savingthrows=0 savebonus=0 END
  END
END


//clone and edit projectile (classic BG2 only)
ACTION_IF (ee_game > 0) BEGIN
  OUTER_SPRINT proj  ~%files%/entangle.pro~
END ELSE BEGIN
  COPY_EXISTING - ~SPPR105.spl~  ~~
    READ_SHORT 0x98 projnum
    SET idsnum = projnum - 1
    LOOKUP_IDS_SYMBOL_OF_INT proj ~projectl~ ~%idsnum%~
END

OUTER_SPRINT res  ~d2cwbs1~
OUTER_SET projarea = 256    // use standard 15-ft. radius

//use iwd proj/sounds
LAF d2_cloneproj STR_VAR copy=~%proj%~ proj=~%res%~ RET projnum END
COPY_EXISTING ~%res%.pro~  ~override~
  PATCH_IF (ee_game > 0) BEGIN
    WRITE_ASCII 0x10   ~~ #8      // fire sound
    WRITE_ASCII 0x18   ~%res%~ #8  // impact sound
    WRITE_ASCII 0x238  ~%res%~ #8  // area sound
  END
  WRITE_SHORT 0x210  100        // explosion frequency
  WRITE_BYTE  0x216  5          // repetitions
  WRITE_SHORT 0x204  projarea   // trap size
  WRITE_SHORT 0x206  projarea   // explosion size
//  WRITE_LONG  0x2c  (THIS | BIT12)  // falling path
  WRITE_SHORT 0x200 (THIS | BIT6)   // enemies only
  WRITE_SHORT 0x200 (THIS | BIT12)  // ignore los
OUTER_SET entangle_proj = projnum
COPY ~%files%/entangle.wav~  ~override/%res%.wav~    // use iwd sound (res conflict with BG games)


//clone entangle (party friendly)
COPY_EXISTING ~SPPR105.spl~  ~override/%res%.SPL~
  LPF spell_edits INT_VAR proj=entangle_proj END
  LPF entangle_edits END

OUTER_TEXT_SPRINT nymph_entangle ~"%res%"~



//install scripts
COPY - ~%nymph%/nymphcore.BAF~  ~inlined/d2cwfey.BAF~
  EVALUATE_BUFFER
  LPF ddoor_check END
COPY - ~%nymph%/nymphalt.BAF~   ~inlined/d2cwfey1.BAF~
  EVALUATE_BUFFER
  LPF ddoor_check END

COMPILE ~inlined/d2cwfey.BAF~
COPY_EXISTING ~d2cwfey.BCS~ ~override/NYMPH.BCS~

COPY - ~inlined/d2cwfey1.BAF~ ~inlined/d2cwfey2.BAF~
  REPLACE_TEXTUALLY ~Player1~ ~Player2~
  REPLACE_TEXTUALLY ~Player0~ ~Player1~
  REPLACE_TEXTUALLY ~d2cwfey2~ ~d2cwfey3~
COPY - ~inlined/d2cwfey1.BAF~ ~inlined/d2cwfey3.BAF~
  REPLACE_TEXTUALLY ~Player1~ ~Player3~
  REPLACE_TEXTUALLY ~Player0~ ~Player1~
  REPLACE_TEXTUALLY ~d2cwfey2~ ~d2cwfey4~
COPY - ~inlined/d2cwfey1.BAF~ ~inlined/d2cwfey4.BAF~
  REPLACE_TEXTUALLY ~Player1~ ~Player4~
  REPLACE_TEXTUALLY ~Player0~ ~Player1~
  REPLACE_TEXTUALLY ~d2cwfey2~ ~d2cwfey5~
COPY - ~inlined/d2cwfey1.BAF~ ~inlined/d2cwfey5.BAF~
  REPLACE_TEXTUALLY ~Player1~ ~Player5~
  REPLACE_TEXTUALLY ~Player0~ ~Player1~
  REPLACE_TEXTUALLY ~d2cwfey2~ ~d2cwfey6~
COPY - ~inlined/d2cwfey1.BAF~ ~inlined/d2cwfey6.BAF~
  REPLACE_TEXTUALLY ~Player1~ ~Player6~
  REPLACE_TEXTUALLY ~Player0~ ~Player1~
  REPLACE_TEXTUALLY ~d2cwfey2~ ~d2cwfey1~
COPY - ~inlined/d2cwfey1.BAF~ ~inlined/d2cwfey1.BAF~
  REPLACE_TEXTUALLY ~Player0~ ~Player1~

COMPILE ~inlined/d2cwfey1.BAF~
COMPILE ~inlined/d2cwfey2.BAF~
COMPILE ~inlined/d2cwfey3.BAF~
COMPILE ~inlined/d2cwfey4.BAF~
COMPILE ~inlined/d2cwfey5.BAF~
COMPILE ~inlined/d2cwfey6.BAF~


//
//