//
//


IF
	!Global("d2Player1initiate","GLOBAL",1)
	OR(2)
		HasItem("%staff%",Player1)
		!Exists(Player1)
	!InParty("nord")    // fix crash with G3 NPC premade party
	!InParty("hildury")
	!InParty("diriel")
	!InParty("jaemal")
	!InParty("salomeya")
	!InParty("nikosh")
THEN
	RESPONSE #100
		SetGlobalTimer("d2Player1start","GLOBAL",6)
		Continue()
END

IF
	!Global("d2Player1initiate","GLOBAL",1)
	GlobalTimerExpired("d2Player1start","GLOBAL")
THEN
	RESPONSE #100
		SetGlobal("d2Player1initiate","GLOBAL",1)
		Continue()
END

IF
	!Global("d2Player1prep","GLOBAL",1)
	GlobalTimerNotExpired("d2Player1start","GLOBAL")
	NumItemsGT("%staff%",Player1,0)
THEN
	RESPONSE #100
		SetGlobalTimer("d2Player1equip","GLOBAL",6)
		Continue()
END

/*
IF
	GlobalTimerNotExpired("d2Player1equip","GLOBAL")
	!Global("d2Player1melee","GLOBAL",1)
	NumItemsGT("%staff%",Player1,0)
THEN
	RESPONSE #100
		ActionOverride(Player1,DestroyItem("%staff%"))
		Continue()
END
*/

IF
	GlobalTimerNotExpired("d2Player1equip","GLOBAL")
	HasItem("%staff%",Player1)
	OR(2)
		!Global("d2Player1melee","GLOBAL",1)
		NumItemsGT("%staff%",Player1,1)
THEN
	RESPONSE #100
		ActionOverride(Player1,DestroyItem("%staff%"))
		SetGlobal("d2Player1prep","GLOBAL",1)
		Continue()
END


//reset m and r variables if melee and ranged variables are not set yet
IF
	!Global("d2Player1melee","GLOBAL",1)
	GlobalTimerNotExpired("d2Player1equip","GLOBAL")
THEN
	RESPONSE #100
		SetGlobal("d2Player1equipm","GLOBAL",0)
		Continue()
END

IF
	!Global("d2Player1ranged","GLOBAL",1)
	GlobalTimerNotExpired("d2Player1equip","GLOBAL")
THEN
	RESPONSE #100
		SetGlobal("d2Player1equipr","GLOBAL",0)
		Continue()
END


/*
*/