# WeiDU Mod Packager by Argent77
# See: https://github.com/InfinityTools/WeiduModPackager

name: 'WeiDU Mod Packager (iemod; multi/win/lin/mac: x64/win32; use tp2 VERSION suffix)'

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  make_64bit_all:
    strategy:
      matrix:
        type: [iemod, windows, linux, macos]

    permissions:
      contents: write

    uses: InfinityTools/WeiduModPackagerLibrary/.github/workflows/WeiduModPackagerLibrary.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: amd64
      suffix: version
      naming: ini
      prefix_windows: windows-x64
      prefix_linux: linux-x64
      prefix_macos: macos-x64
      name_fmt: '<%base_name%><-%version%><-%os_prefix%>'
      lower_case: true

  make_64bit_multi:
    strategy:
      matrix:
        type: [multi]

    permissions:
      contents: write

    uses: InfinityTools/WeiduModPackagerLibrary/.github/workflows/WeiduModPackagerLibrary.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: amd64
      suffix: version
      extra: multi-x64
      naming: ini
      name_fmt: '<%base_name%><-%version%><-%extra%>'
      lower_case: true

  make_32bit_win:
    strategy:
      matrix:
        type: [windows]

    permissions:
      contents: write

    uses: InfinityTools/WeiduModPackagerLibrary/.github/workflows/WeiduModPackagerLibrary.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: x86
      suffix: version
      naming: ini
      prefix_windows: windows-x86
      name_fmt: '<%base_name%><-%version%><-%os_prefix%>'
      lower_case: true
